language: csharp
solution: DSmall.Core.sln
install:
  - nuget restore DSmall.Core.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release DSmall.Core.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./DSmall.Core.UnitTest/bin/Release/DSmall.Core.UnitTest.dll